apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  namespace: default
  labels:
    app: ui-web-app 
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080 
  selector:
    app: ui-web-app
  type: NodePort
